#pragma once
/**
 * @file glsl.hpp
 * @author karurochari
 * @brief Dynamic GLSL shader generator for the kd3 library.
 * @date 2026-05-15
 * 
 * @copyright Copyright (c) 2026
 */

/*
    Warning: This generator only covers a subset of all possible configurations, mostly as they are limited by GLSL native types.
*/

#include <string>
#include <sstream>
#include <algorithm>
#include <cctype>

#include "query.hpp"

namespace kd3 {

struct GlslConfigDyn {
    private:
        static constexpr cfg_t cfg{};
    public:
        std::string prefix = "kd3";
        uint32_t binding_vals = 0;
        uint32_t binding_dims = 1;
        uint32_t binding_bks = 2;
        uint32_t max_k = 8;

        size_t D=3;

        //From cfg_t

        size_t leaf_size = cfg.leaf_size;
        cfg_t::has_payload_t has_payload = cfg.has_payload;
        size_t max_stack_depth = cfg.max_stack_depth;
        size_t simd_parallelism = cfg.simd_parallelism;
};

struct GlslConfig {
    uint32_t binding_vals = 0;
    uint32_t binding_dims = 1;
    uint32_t binding_bks = 2;
    uint32_t max_k = 8;
    uint32_t max_stack_depth =48*2;
};

inline std::string generate_glsl_dyn(const GlslConfigDyn& glsl_cfg = {}) {
    if (glsl_cfg.D < 2 || glsl_cfg.D > 4) {
        return "#error \"kd3 GLSL generator only supports 2D, 3D, and 4D trees.\\n\"\n";
    }
    
    std::string P = glsl_cfg.prefix;
    std::string P_Title = P;
    if (!P_Title.empty()) P_Title[0] = static_cast<char>(std::toupper(static_cast<unsigned char>(P_Title[0])));

    std::string vec_type = "vec" + std::to_string(glsl_cfg.D);
    
    // Calculate layout constants matching C++
    size_t align_bytes = std::min<size_t>(64, glsl_cfg.simd_parallelism * 8);
    size_t align_words = align_bytes / 4;
    if (align_words == 0) align_words = 1;
    
    size_t coords_words = glsl_cfg.D * glsl_cfg.leaf_size;
    size_t ids_words = glsl_cfg.has_payload!=cfg_t::has_payload_t::NONE ? glsl_cfg.leaf_size : 0;
    size_t payload_words = coords_words + ids_words;
    size_t bucket_words = ((payload_words + align_words - 1) / align_words) * align_words;

    // View constants
    size_t dim_bits = [&]() {
        if (glsl_cfg.D <= 2) return 1;
        else if (glsl_cfg.D <= 4) return 2;
        else if (glsl_cfg.D <= 16) return 4;
        else return 8; // Max 256 dimensions
    }();
    size_t dim_mask = (1ULL << dim_bits) - 1;;
    size_t dims_per_word = 64 / dim_bits;
    
    std::ostringstream oss;
    
    oss << "// Generated by kd3::generate_glsl\n";
    if (glsl_cfg.has_payload != cfg_t::has_payload_t::NONE) {
        oss << "struct " << P_Title << "KnnResult { float dist_sq; uint payload_id; };\n";
        oss << "struct " << P_Title << "RayHit { float t; uint payload_id; };\n\n";
    }

    oss << "layout(std430, binding = " << glsl_cfg.binding_vals << ") readonly buffer " << P_Title << "SplitVals { float " << P << "_split_vals[]; };\n";
    oss << "layout(std430, binding = " << glsl_cfg.binding_dims << ") readonly buffer " << P_Title << "SplitDims { uint64_t " << P << "_split_dims[]; };\n";
    oss << "layout(std430, binding = " << glsl_cfg.binding_bks << ")  readonly buffer " << P_Title << "Buckets   { uint " << P << "_buckets[]; };\n\n";

    oss << "uint " << P << "_get_dim(uint i) {\n";
    oss << "    uint idx = i / " << dims_per_word << "u;\n";
    oss << "    uint offset = (i % " << dims_per_word << "u) * " << dim_bits << "u;\n";
    oss << "    return uint(" << P << "_split_dims[idx] >> offset) & " << dim_mask << "u;\n";
    oss << "}\n\n";

    auto gen_ray_logic = [&](bool with_index) {
        if (with_index) {
            oss << "bool " << P << "_query_ray(" << vec_type << " ro, " << vec_type << " rd, float max_t, float epsilon, " << vec_type << " root_bmin, " << vec_type << " root_bmax, out " << P_Title << "RayHit result) {\n";
        } else {
            oss << "bool " << P << "_query_ray_distance(" << vec_type << " ro, " << vec_type << " rd, float max_t, float epsilon, " << vec_type << " root_bmin, " << vec_type << " root_bmax, out float out_t) {\n";
        }

        oss << "    uint num_buckets = uint(" << P << "_buckets.length()) / " << bucket_words << "u;\n";
        oss << "    if (num_buckets == 0u) return false;\n\n";
        
        oss << "    " << vec_type << " inv_rd = 1.0 / mix(rd, " << vec_type << "(1e-8), equal(rd, " << vec_type << "(0.0)));\n";
        oss << "    " << vec_type << " abs_inv_rd = abs(inv_rd);\n";
        oss << "    " << vec_type << " voxel_extent = epsilon * abs_inv_rd;\n\n";
        
        oss << "    " << vec_type << " t1_aabb = (root_bmin - ro) * inv_rd;\n";
        oss << "    " << vec_type << " t2_aabb = (root_bmax - ro) * inv_rd;\n";
        
        oss << "    " << vec_type << " min_aabb = min(t1_aabb, t2_aabb);\n";
        oss << "    " << vec_type << " max_aabb = max(t1_aabb, t2_aabb);\n";
        if (glsl_cfg.D == 2) {
            oss << "    float tN = max(max(min_aabb.x, min_aabb.y), 0.0);\n";
            oss << "    float tF = min(min(max_aabb.x, max_aabb.y), max_t);\n";
        } else if (glsl_cfg.D == 3) {
            oss << "    float tN = max(max(min_aabb.x, min_aabb.y), max(min_aabb.z, 0.0));\n";
            oss << "    float tF = min(min(max_aabb.x, max_aabb.y), min(max_aabb.z, max_t));\n";
        } else if (glsl_cfg.D == 4) {
            oss << "    float tN = max(max(min_aabb.x, min_aabb.y), max(min_aabb.z, max(min_aabb.w, 0.0)));\n";
            oss << "    float tF = min(min(max_aabb.x, max_aabb.y), min(max_aabb.z, min(max_aabb.w, max_t)));\n";
        }
        
        oss << "    if (tN > tF) return false;\n\n";
        
        oss << "    uint stack_idx[" << glsl_cfg.max_stack_depth << "];\n";
        oss << "    float stack_t_min[" << glsl_cfg.max_stack_depth << "];\n";
        oss << "    float stack_t_max[" << glsl_cfg.max_stack_depth << "];\n";
        oss << "    uint stack_sz = 0u;\n\n";
        
        oss << "    stack_idx[0] = 0u; stack_t_min[0] = tN; stack_t_max[0] = tF; stack_sz++;\n\n";
        
        oss << "    float best_t = max_t;\n";
        if (with_index) {
            oss << "    uint best_id = 0xFFFFFFFFu;\n";
        }
        oss << "    uint LEAF_THRESHOLD = num_buckets - 1u;\n\n";
        
        oss << "    while (stack_sz > 0u) {\n";
        oss << "        stack_sz--;\n";
        oss << "        uint curr = stack_idx[stack_sz];\n";
        oss << "        float t_min = stack_t_min[stack_sz];\n";
        oss << "        float node_t_max = stack_t_max[stack_sz];\n\n";
        
        oss << "        if (t_min >= best_t) continue;\n\n";
        
        oss << "        if (curr >= LEAF_THRESHOLD) {\n";
        oss << "            uint base = (curr - LEAF_THRESHOLD) * " << bucket_words << "u;\n";
        if (with_index) {
            oss << "            uint id_base = base + " << coords_words << "u;\n";
        }
        
        oss << "            for (uint i = 0u; i < " << glsl_cfg.leaf_size << "u; ++i) {\n";
        oss << "                " << vec_type << " b = " << vec_type << "(\n";
        for (size_t d = 0; d < glsl_cfg.D; ++d) {
            oss << "                    uintBitsToFloat(" << P << "_buckets[base + " << d * glsl_cfg.leaf_size << "u + i])" << (d + 1 == glsl_cfg.D ? "" : ",") << "\n";
        }
        oss << "                );\n";
        
        oss << "                " << vec_type << " C1 = (b - ro) * inv_rd;\n";
        oss << "                " << vec_type << " t1 = C1 - voxel_extent;\n";
        oss << "                " << vec_type << " t2 = C1 + voxel_extent;\n";
        
        if (glsl_cfg.D == 2) {
            oss << "                float tn = max(max(t1.x, t1.y), 0.0);\n";
            oss << "                float tf = min(min(t2.x, t2.y), best_t);\n";
        } else if (glsl_cfg.D == 3) {
            oss << "                float tn = max(max(t1.x, t1.y), max(t1.z, 0.0));\n";
            oss << "                float tf = min(min(t2.x, t2.y), min(t2.z, best_t));\n";
        } else if (glsl_cfg.D == 4) {
            oss << "                float tn = max(max(t1.x, t1.y), max(t1.z, max(t1.w, 0.0)));\n";
            oss << "                float tf = min(min(t2.x, t2.y), min(t2.z, min(t2.w, best_t)));\n";
        }
        
        oss << "                if (tn <= tf && tn < best_t) {\n";
        oss << "                    best_t = tn;\n";
        if (with_index) oss << "                    best_id = " << P << "_buckets[id_base + i];\n";
        oss << "                }\n";
        oss << "            }\n";
        oss << "            continue;\n";
        oss << "        }\n\n";
        
        oss << "        uint dim = " << P << "_get_dim(curr);\n";
        oss << "        float split = " << P << "_split_vals[curr];\n";
        
        oss << "        float ro_dim = ro[dim];\n";
        oss << "        float rd_dim = rd[dim];\n";
        oss << "        float inv_rd_dim = inv_rd[dim];\n\n";
        
        oss << "        uint left_child = 2u * curr + 1u;\n";
        oss << "        uint right_child = 2u * curr + 2u;\n\n";
        
        oss << "        uint first = (rd_dim >= 0.0) ? left_child : right_child;\n";
        oss << "        uint second = (rd_dim >= 0.0) ? right_child : left_child;\n\n";
        
        oss << "        float t_split = (split - ro_dim) * inv_rd_dim;\n";
        oss << "        float t_margin = epsilon * abs(inv_rd_dim);\n\n";
        
        oss << "        float t_enter_second = t_split - t_margin;\n";
        oss << "        float t_leave_first  = t_split + t_margin;\n\n";
        
        oss << "        bool visit_first  = t_min <= t_leave_first;\n";
        oss << "        bool visit_second = node_t_max >= t_enter_second;\n\n";
        
        oss << "        if (visit_first && visit_second) {\n";
        oss << "            stack_idx[stack_sz] = second; stack_t_min[stack_sz] = max(t_min, t_enter_second); stack_t_max[stack_sz] = node_t_max; stack_sz++;\n";
        oss << "            stack_idx[stack_sz] = first;  stack_t_min[stack_sz] = t_min; stack_t_max[stack_sz] = min(node_t_max, t_leave_first); stack_sz++;\n";
        oss << "        } else {\n";
        oss << "            stack_idx[stack_sz] = visit_first ? first : second;\n";
        oss << "            stack_t_min[stack_sz] = t_min;\n";
        oss << "            stack_t_max[stack_sz] = node_t_max;\n";
        oss << "            stack_sz++;\n";
        oss << "        }\n";
        oss << "    }\n\n";
        
        if (with_index) {
            oss << "    if (best_id != 0xFFFFFFFFu) {\n";
            oss << "        result.t = best_t;\n";
            oss << "        result.payload_id = best_id;\n";
            oss << "        return true;\n";
            oss << "    }\n";
            oss << "    return false;\n";
        } else {
            oss << "    if (best_t < max_t) {\n";
            oss << "        out_t = best_t;\n";
            oss << "        return true;\n";
            oss << "    }\n";
            oss << "    return false;\n";
        }
        oss << "}\n\n";
    };

    if (glsl_cfg.has_payload!=cfg_t::has_payload_t::NONE) {
        gen_ray_logic(true);
    }
    gen_ray_logic(false);

    auto gen_knn_logic = [&](bool with_index, bool multi) {
        if (with_index) {
            if (multi) {
                oss << "uint " << P << "_query_knn(" << vec_type << " target, uint k, out " << P_Title << "KnnResult results[" << glsl_cfg.max_k << "]) {\n";
            } else {
                oss << "bool " << P << "_query_1nn(" << vec_type << " target, out " << P_Title << "KnnResult result) {\n";
            }
        } else {
            oss << "bool " << P << "_query_distance2(" << vec_type << " target, out float out_dist_sq) {\n";
        }
        
        oss << "    uint num_buckets = uint(" << P << "_buckets.length()) / " << bucket_words << "u;\n";
        if (multi) oss << "    if (num_buckets == 0u || k == 0u) return 0u;\n\n";
        else oss << "    if (num_buckets == 0u) return false;\n\n";

        if (multi) {
            oss << "    uint count = 0u;\n";
        } else {
            oss << "    float min_dist_sq = 1e38;\n";
            if (with_index) oss << "    uint best_id = 0xFFFFFFFFu;\n";
        }

        oss << "    uint stack_idx[" << glsl_cfg.max_stack_depth << "];\n";
        oss << "    float stack_dist[" << glsl_cfg.max_stack_depth << "];\n";
        oss << "    uint stack_sz = 0u;\n\n";
        
        oss << "    stack_idx[0] = 0u; stack_dist[0] = 0.0; stack_sz++;\n";
        oss << "    uint LEAF_THRESHOLD = num_buckets - 1u;\n\n";

        oss << "    while (stack_sz > 0u) {\n";
        oss << "        stack_sz--;\n";
        oss << "        uint curr = stack_idx[stack_sz];\n";
        oss << "        float node_min_dist = stack_dist[stack_sz];\n\n";

        if (multi) {
            oss << "        if (count == k && node_min_dist >= results[k - 1u].dist_sq) continue;\n\n";
        } else {
            oss << "        if (node_min_dist >= min_dist_sq) continue;\n\n";
        }

        oss << "        if (curr >= LEAF_THRESHOLD) {\n";
        oss << "            uint base = (curr - LEAF_THRESHOLD) * " << bucket_words << "u;\n";
        if (with_index) {
            oss << "            uint id_base = base + " << coords_words << "u;\n";
        }
        
        oss << "            for (uint i = 0u; i < " << glsl_cfg.leaf_size << "u; ++i) {\n";
        oss << "                " << vec_type << " b = " << vec_type << "(\n";
        for (size_t d = 0; d < glsl_cfg.D; ++d) {
            oss << "                    uintBitsToFloat(" << P << "_buckets[base + " << d * glsl_cfg.leaf_size << "u + i])" << (d + 1 == glsl_cfg.D ? "" : ",") << "\n";
        }
        oss << "                );\n";
        oss << "                " << vec_type << " diff = target - b;\n";
        oss << "                float dist_sq = dot(diff, diff);\n";

        if (multi) {
            oss << "                if (count < k || dist_sq < results[k - 1u].dist_sq) {\n";
            oss << "                    uint pos = count;\n";
            oss << "                    if (pos == k) pos = k - 1u;\n";
            oss << "                    else count++;\n";
            oss << "                    while (pos > 0u && results[pos - 1u].dist_sq > dist_sq) {\n";
            oss << "                        results[pos] = results[pos - 1u];\n";
            oss << "                        pos--;\n";
            oss << "                    }\n";
            oss << "                    results[pos] = " << P_Title << "KnnResult(dist_sq, " << P << "_buckets[id_base + i]);\n";
            oss << "                }\n";
        } else {
            oss << "                if (dist_sq < min_dist_sq) {\n";
            oss << "                    min_dist_sq = dist_sq;\n";
            if (with_index) oss << "                    best_id = " << P << "_buckets[id_base + i];\n";
            oss << "                }\n";
        }
        oss << "            }\n";
        oss << "            continue;\n";
        oss << "        }\n\n";

        oss << "        uint dim = " << P << "_get_dim(curr);\n";
        oss << "        float split = " << P << "_split_vals[curr];\n";
        oss << "        float axis_dist = target[dim] - split;\n";
        oss << "        float axis_dist_sq = axis_dist * axis_dist;\n";
        
        oss << "        uint left = 2u * curr + 1u;\n";
        oss << "        uint right = 2u * curr + 2u;\n";
        oss << "        uint first = (axis_dist < 0.0) ? left : right;\n";
        oss << "        uint second = (axis_dist < 0.0) ? right : left;\n\n";

        if (multi) {
            oss << "        if (count < k || axis_dist_sq < results[k - 1u].dist_sq) {\n";
        } else {
            oss << "        if (axis_dist_sq < min_dist_sq) {\n";
        }
        oss << "            stack_idx[stack_sz] = second; stack_dist[stack_sz] = axis_dist_sq; stack_sz++;\n";
        oss << "        }\n";
        oss << "        stack_idx[stack_sz] = first; stack_dist[stack_sz] = 0.0; stack_sz++;\n";
        oss << "    }\n\n";

        if (multi) {
            oss << "    uint valid_results = 0u;\n";
            oss << "    for (uint i = 0u; i < count; ++i) if (results[i].dist_sq < 1e29) valid_results++;\n";
            oss << "    return valid_results;\n";
            oss << "}\n\n";
        } else {
            oss << "    if (min_dist_sq >= 1e29) return false;\n";
            if (with_index) {
                oss << "    result.dist_sq = min_dist_sq;\n";
                oss << "    result.payload_id = best_id;\n";
            } else {
                oss << "    out_dist_sq = min_dist_sq;\n";
            }
            oss << "    return true;\n";
            oss << "}\n\n";
        }
    };

    if(glsl_cfg.has_payload!=cfg_t::has_payload_t::NONE) {
        gen_knn_logic(true, false);
        gen_knn_logic(true, true);
    }
    gen_knn_logic(false, false);

    return oss.str();
}

//Static interface, just to simplify usage by passing the same building args of a tree
template<typename Limits, cfg_t cfg={}, GlslConfig glsl_cfg={}>
std::string generate_glsl(const std::string& ns="kd3"){
    static_assert(std::is_same_v<typename Limits::scalar_t,float> && std::is_same_v<typename Limits::distance_t,float>, "Generation of GLSL shader only allowed for float for now");
    static_assert(std::is_same_v<typename Limits::payload_t,uint32_t>, "Generation of GLSL shader only allowed for uint32_t index/payload for now");

    return generate_glsl_dyn({
        .prefix=ns,
        .binding_vals=glsl_cfg.binding_vals,
        .binding_dims=glsl_cfg.binding_dims,
        .binding_bks=glsl_cfg.binding_bks,
        .max_k=glsl_cfg.max_k,

        .D=Limits::D,

        .leaf_size = cfg.leaf_size,
        .has_payload = cfg.has_payload,
        .max_stack_depth=cfg.max_stack_depth,
        .simd_parallelism=cfg.simd_parallelism,
    });
}

} // namespace kd3
